---
- name: Verify Rocky Linux distribution and version
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == 'Rocky'
      - ansible_facts['distribution_major_version'] in ['8', '9']
    fail_msg: "Supports RockyLinux versions 8 or 9. Detected: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}."
    success_msg: "Running on RockyLinux {{ ansible_facts['distribution_major_version'] }}."

- name: Enable Red Hat Enterprise Linux Identity Management system module on RockyLinux 8
  ansible.builtin.dnf:
    name: "@idm:DL1"
    state: present
  when:
    - ansible_facts['distribution'] == 'Rocky' and ansible_facts['distribution_major_version'] == '8'
