---
- name: Validate user inputs
  ansible.builtin.assert:
    that:
      - ipa_domain is string
      - ipa_server_hostname is string
    fail_msg: "Input validation failed. See README.md for information on required inputs and their format."
    success_msg: "User input configuration is valid."

- name: Verify Rocky Linux distribution and version
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == 'Rocky'
      - ansible_facts['distribution_major_version'] in ['8', '9']
    fail_msg: "Supports RockyLinux versions 8 or 9. Detected: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}."
    success_msg: "Running on RockyLinux {{ ansible_facts['distribution_major_version'] }}."

- name: Enable Red Hat Enterprise Linux Identity Management system module on RockyLinux 8
  ansible.builtin.dnf:
    name: "@idm:DL1"
    state: present
  when:
    - ansible_facts['distribution'] == 'Rocky' and ansible_facts['distribution_major_version'] == '8'

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - firewalld
      - ipa-server
      - ipa-server-dns
      - bind-dyndb-ldap
      - dnf-automatic
    state: present

- name: SSH - Disallow root SSH access
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd

- name: SElinux - Set permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ ipa_server_hostname }}.{{ ipa_domain }}"
    use: systemd
  register: hostname_set
  changed_when: hostname_set.changed

- name: Persist hostname to /etc/hostname
  ansible.builtin.copy:
    dest: /etc/hostname
    content: "{{ ipa_server_hostname }}.{{ ipa_domain }}\n"
    mode: '0644'
  register: hostname_persist
  changed_when: hostname_persist.changed

- name: Add server /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: '{{ ansible_default_ipv4.address }} {{ ipa_server_hostname }}.{{ ipa_domain }}'
    insertafter: BOF
    state: present

- name: Configure DNS server in NetworkManager
  community.general.nmcli:
    conn_name: "{{ ansible_default_ipv4.interface }}"
    type: ethernet
    dns4:
      - "127.0.0.1"
    state: present
  notify: Reload NetworkManager

- name: Check if FreeIPA is already installed
  ansible.builtin.stat:
    path: /etc/ipa/default.conf
  register: ipa_config_stat

- name: Install and configure the IPA server
  ansible.builtin.command:
    argv:
      - ipa-server-install
      - --unattended
      - --domain={{ ipa_domain }}
      - --mkhomedir
      - --setup-dns
      - --auto-reverse
      - --forwarder={{ openstack_subnet_dns_nameserver_ip_default }}
      - --forwarder={{ openstack_subnet_dns_nameserver_ip_fallback }}
      - --realm={{ ipa_domain | upper }}
      - --hostname={{ ipa_server_hostname }}.{{ ipa_domain }}
      - --ds-password={{ ipa_admin_password }}
      - --admin-password={{ ipa_admin_password }}
    creates: /etc/ipa/default.conf
  when: not ipa_config_stat.stat.exists
  register: ipa_install_result
  failed_when: ipa_install_result.rc != 0 and 'already installed' not in ipa_install_result.stderr

- name: Configure DNF-automatic update_type
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "^upgrade_type"
    line: "upgrade_type = security"
    state: present

- name: Configure DNF-automatic download_updates
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "^download_updates"
    line: "download_updates = yes"
    state: present

- name: Configure DNF-automatic apply_updates
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "^apply_updates"
    line: "apply_updates = yes"
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: List installed package versions
  ansible.builtin.debug:
    msg:
      - "firewalld: {{ ansible_facts.packages['firewalld'][0].version }}-{{ ansible_facts.packages['firewalld'][0].release }}"
      - "ipa-server: {{ ansible_facts.packages['ipa-server'][0].version }}-{{ ansible_facts.packages['ipa-server'][0].release }}"
      - "ipa-server-dns: {{ ansible_facts.packages['ipa-server-dns'][0].version }}-{{ ansible_facts.packages['ipa-server-dns'][0].release }}"
      - "bind-dyndb-ldap: {{ ansible_facts.packages['bind-dyndb-ldap'][0].version }}-{{ ansible_facts.packages['bind-dyndb-ldap'][0].release }}"
      - "dnf-automatic: {{ ansible_facts.packages['dnf-automatic'][0].version }}-{{ ansible_facts.packages['dnf-automatic'][0].release }}"
