---
- name: Verify Rocky Linux distribution and version
  ansible.builtin.assert:
    that:
      - ansible_facts['distribution'] == 'Rocky'
      - ansible_facts['distribution_major_version'] in ['8', '9']
    fail_msg: "Supports RockyLinux versions 8 or 9. Detected: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }}."
    success_msg: "Running on RockyLinux {{ ansible_facts['distribution_major_version'] }}."

- name: Enable Red Hat Enterprise Linux Identity Management system module on RockyLinux 8
  ansible.builtin.dnf:
    name: "@idm:DL1"
    state: present
  when:
    - ansible_facts['distribution'] == 'Rocky' and ansible_facts['distribution_major_version'] == '8'

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - firewalld
      - ipa-server
      - ipa-server-dns
      - bind-dyndb-ldap
      - dnf-automatic
    state: present

- name: SSH - Disallow root SSH access
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart sshd

- name: SElinux - Set permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: List installed package versions
  ansible.builtin.debug:
    msg:
      - "firewalld: {{ ansible_facts.packages['firewalld'][0].version }}-{{ ansible_facts.packages['firewalld'][0].release }}"
      - "ipa-server: {{ ansible_facts.packages['ipa-server'][0].version }}-{{ ansible_facts.packages['ipa-server'][0].release }}"
      - "ipa-server-dns: {{ ansible_facts.packages['ipa-server-dns'][0].version }}-{{ ansible_facts.packages['ipa-server-dns'][0].release }}"
      - "bind-dyndb-ldap: {{ ansible_facts.packages['bind-dyndb-ldap'][0].version }}-{{ ansible_facts.packages['bind-dyndb-ldap'][0].release }}"
      - "dnf-automatic: {{ ansible_facts.packages['dnf-automatic'][0].version }}-{{ ansible_facts.packages['dnf-automatic'][0].release }}"
